#
# SMPCore v2.1 Configuration File
#

server:
  motd: TotalFreedom SMP (MC 1.15.2 & 1.16.1) - Stay Home
  tablist_header: ' \n  &dWelcome to &6TotalFreedom SMP&d!  \n '
  tablist_footer: ' \n  &d#StayHome \n  '
  coords:
    worldspawn:
      x: 0
      y: 63
      z: 0
    shop:
      x: -192
      y: 4
      z: -203
  rules:
    - '&dFor a list of server rules, please visit: &6https://smp.totalfreedom.me/rules&d.'
  announcer:
    enabled: true
    interval: 600
    prefix: '&dSMP » &6'
    announcements:
      - fionn is the owner of the SMP.
      - Hacked clients are not allowed!
      - Make sure to read our conduct policy at &dhttps://smp.totalfreedom.me/rules &6& &dhttps://totalfreedom.boards.net/thread/66475/smp-conduct-policy
      - Griefing / Raiding is not allowed!
      - Join our Discord server! &dhttps://discord.gg/EJ77jDD
      - Do &d/shop &6to visit the shop!
      - Do &d/crate &6to visit the crates!
      - Do &d/worldspawn &6to go to 0, 0!