#
# SMPCore v2.4 Configuration File
#

server:
  tablist_header: ' \n  &dWelcome to &6TotalFreedom SMP&d!  \n '
  tablist_footer: ' \n  &d#StayHome \n  '
  coords:
    worldspawn:
      x: 0
      y: 63
      z: 0
  rules:
    - '&dFor a list of server rules, please visit: &6https://smp.totalfreedom.me/rules&d.'
  announcer:
    enabled: true
    interval: 600
    prefix: '&dSMP » &6'
    announcements:
      - Hacked clients are not allowed!
      - Make sure to read our conduct policy at &dhttps://smp.totalfreedom.me/rules
        &6& &dhttps://totalfreedom.boards.net/thread/66475/smp-conduct-policy
      - Griefing / Raiding is allowed!
      - Join our Discord server! &dhttps://discord.gg/EJ77jDD
      - Do &d/worldspawn &6to go to 0, 0!
      - The Dynmap link for SMP is: http://smp.totalfreedom.me:1694/
      - You can create a new faction by typing &d/f create <name>
      - Server lagging? You can check the lag with "/tps"
      - You can visit the TotalFreedom forums at: https://forum.totalfreedom.me
      - To learn more about SMPItems, check out the wiki at: https://smp.totalfreedom.me/wiki/
      - To get a list of server links, type &d/links
      - To vote for the server, type &d/vote
links:
  - '&dForums &8- &6https://forum.totalfreedom.me'
  - '&dSMPItems Wiki &8- &6https://smp.totalfreedom.me/wiki/Main_Page'
  - '&dDynmap &8- &6http://smp.totalfreedom.me:1694'
  - '&dServer Rules &8- &6https://smp.totalfreedom.me/rules'
  - '&dDiscord &8- &6https://discord.gg/PfWy8dC'
voting:
  - '&dPMC &8- &6https://www.planetminecraft.com/server/totalfreedom-smp/vote/'
  - '&dTopG &8- &6https://topg.org/Minecraft/in-610732'
  - '&dMCSL &8- &6https://minecraft-server-list.com/server/464127/vote/'