#
# TF-SMP v1.2 Configuration File
#

server:
  motd: "TotalFreedom SMP (MC 1.15.2) - Stay Home"
  tablist_header: ' \n  &bWelcome to &eTotalFreedom SMP&b!  \n '
  tablist_footer: ' \n  &b#StayHome \n  '