name: SMPCore
version: ${project.version}
main: me.totalfreedom.smp.SMPCore
author: Telesphoreo
description: Plugin for the TotalFreedom SMP server
softdepend: [LuckPerms, WorldBorder]
api-version: 1.15
commands:
  adminchat:
    usage: /<command> <message>
    description: Speak with other staff members
    aliases: [o, oc, adminchat, ac]
  announce:
    usage: /<command> <message>
    description: Announces a message
    aliases: [an, broadcast]
  begin:
    description: Get started with SMP
    usage: /<command>
  clearweather:
    description: Clears the weather in all worlds
    usage: /<command>
  consolesay:
    description: Send a message from the console
    usage: /<command> <message>
    aliases: [csay]
  kill:
    usage: /<command> [player]
    description: Kills you or if you have permissions, another player
    aliases: [suicide, ekill, esuicide]
  links:
    usage: /<command>
    description: Get a list of links relevant to the server.
  localspawn:
    usage: /<command>
    description: Teleport to the spawnpoint of the world that you are in
  # Override Essentials tprandom
  randomtp:
    description: Randomly teleport to a location
    usage: /<command>
    aliases: [rtp, tpr, tprandom, etprandom, etpr]
  rawsay:
    description: Broadcasts a message
    usage: /<command> <message>
  rules:
    description: View the server rules
    usage: /<command>
    aliases: [erules]
  satisfyall:
    description: Feed and heal everyone online
    usage: /<command>
  say:
    description: Talk as the server
    usage: /<command> <message>
  smpcore:
    description: Shows information about the SMP plugin or optionally reloads it
    usage: /<command> [reload]
    aliases: [totalfreedommod, tfm, converse, novelmcsucks, novelmcisdead, versatility]
  vote:
    description: Shows a list of all the voting links
    usage: /<command>
  worldspawn:
    description: Teleports player to 0, 0
    usage: /<command>
    aliases: [localspawn]