name: TF-SMP
version: ${project.version}
main: me.totalfreedom.smp.TFSMP
author: Telesphoreo
description: Plugin for the TotalFreedom SMP server.
softdepend: [LuckPerms]
api-version: 1.15
commands:
  adminchat:
    usage: /<command> <message>
    description: Speak with other staff members
    aliases: [o, oc, adminchat, ac]
  begin:
    description: Get started with SMP.
    usage: /<command>
  clearweather:
    description: Clears the weather in all worlds
    usage: /<command>
  consolesay:
    description: Send a message from the console
    usage: /<command> <message>
    aliases: [csay]
  crate:
    usage: /<command>
    description: Teleports player to the crate location
  fionn:
    usage: /<command>
    description: Yeah!
  owo:
    usage: /<command>
    description: Owo!
  randomtp:
    description: Randomly teleport to a location
    usage: /<command>
    aliases: [rtp, tpr]
  rawsay:
    description: Broadcasts a message
    usage: /<command> <message>
  satisfyall:
    description: Feed and heal everyone online
    usage: /<command>
  say:
    description: Talk as the server
    usage: /<command> <message>
  shop:
    description: Teleports the player to the shop location
    usage: /<command>
  smp:
    description: Shows information about the SMP plugin or optionally reloads it.
    usage: /<command> [reload]
    aliases: [tfsmp, totalfreedommod, tfm, converse, novelmcsucks, novelmcisdead, versatility]
  worldspawn:
    description: Teleports player to 0, 0
    usage: /<command>
    aliases: [localspawn]
  uhoh:
    description: Uh oh! Stinky!
    usage: /<command>