name: TF-SMP
version: ${project.version}
main: me.totalfreedom.smp.TFSMP
author: Telesphoreo
description: Plugin for the TotalFreedom SMP server.
api-version: 1.15
commands:
  adminchat:
    usage: /<command> <message>
    description: Speak with other staff members
    aliases: [o, oc, adminchat, ac]
    permission: tfsmp.adminchat
  begin:
    description: Get started with SMP.
    usage: /<command>
  clearweather:
    description: Clears the weather in all worlds
    usage: /<command>
  crate:
    usage: /<command>
    description: Teleports player to the crate location
  fionn:
    usage: /<command>
    description: Yeah!
  powerboost:
    permission: tfsmp.powerboost
    description: Powerboost your faction
    usage: /<command>
  randomtp:
    description: Randomly teleport to a location
    usage: /<command>
    aliases: [rtp]
  satisfyall:
    permission: tfsmp.satisfyall
    description: Feed and heal everyone
    usage: /<command>
  say:
    description: Talk as the server
    usage: /<command> <message>
    permission: tfsmp.say
  shop:
    description: Teleports the player to the shop location
    usage: /<command>
  smp:
    description: Shows information about the SMP plugin or optionally reloads it.
    usage: /<command> [reload]
  worldspawn:
    description: Teleports player to 0, 0
    usage: /<command>