name: TF-SMP
version: 1.1
main: me.totalfreedom.smp.TFSMP
author: Telesphoreo
description: Plugin for the TotalFreedom SMP server.
api-version: 1.15
commands:
  begin:
    permission: smp.warp
    description: Randomly Teleport
    usage: /begin
  chatall:
    permission: IvanUtilities.OP
    description: Chat as everyone.
    usage: /chatall message
  clearweather:
    permission: IvanUtilities.default
    description: Clears weather in all worlds
    usage: /weather
  crate:
    usage: /<command>
    description: Teleports player to the crate location
  fionn:
    usage: /<command>
    description: Yeah!
  importantmessage:
    permission: IvanUtilities.OP
    description: Important Message
    usage: /importantmessage message
  opchat:
    aliases: [o, oc, adminchat, ac]
    permission: IvanUtilities.OP
    description: Speak with other OPs
    usage: /opchat message
  owo:
    permission: IvanUtilities.OP
    description: Owo!
    usage: /owo
  powerboost:
    permission: IvanUtilities.default
    description: Powerboost faction
    usage: /powerboost <faction>
  randomtp:
    description: Randomly teleport to a location
    usage: /<command>
    aliases: [rtp]
  strikeall:
    permission: IvanUtilities.OP
    description: Strike all!
    usage: /<command>
  shop:
    description: Teleports the player to the shop location
    usage: /<command>
  worldspawn:
    description: Teleports player to 0, 0
    usage: /<command>
  satisfyall:
    permission: IvanUtilities.OP
    description: Feed and Heal everyone
    usage: /satisfyall
  uhoh:
    permission: IvanUtilities.OP
    description: Uh oh! Stinky!
    usage: /uhoh

permissions:
  IvanUtilities.OP:
    description: Gives access to all commands
    default: op
  IvanUtilities.troll:
    description: Gives access to some commands
    default: op
  IvanUtilities.default:
    description: idiot
    default: op
  smp.warp:
    description: bruh
    default: op